### ISSUE TITLE
OutofMemoryException while executing median cut algorithm on large image

### ISSUE THREAD

**Issue by ialok** [spatial-computing/strabo-text-recognition#6]
> ### Background 
We use [median-cut](https://en.wikipedia.org/wiki/Median_cut#Implementation_of_color_quantization) algorithm for color quantization. For this process, Strabo uses the methods provided by the [nQuant](https://nquant.codeplex.com/) library (ver=1.0.3) 

> ### Issue(s)
_`QuantizeImage`_ method of _`WuQuantizer`_ class fails to quantize large images

##### Input Image dimensions
Original Size | Original Colors | Number of unique Colors | File Size
-------------- | ---------------- | ---------------------------- | ---------
6454 x 8031 | 16,7 Million   (24 BitsPerPixel) | 2485530 | 148.41 MB (155,619,280 Bytes)

`3/10/2017 2:33:10 PM ColorSegmentationWorker:` **`Exception of type 'System.OutOfMemoryException' was thrown.`** 

```
3/10/2017 2:33:10 PM ColorSegmentationWorker: Exception of type 'System.OutOfMemoryException' was thrown.
3/10/2017 2:33:10 PM nQuant.Core
3/10/2017 2:33:10 PM    at nQuant.ColorData..ctor(Int32 dataGranularity, Int32 bitmapWidth, Int32 bitmapHeight) in c:\dev\nquant\nQuant.Core\ColorData.cs:line 19
   at nQuant.WuQuantizerBase.BuildHistogram(Bitmap sourceImage, Int32 alphaThreshold, Int32 alphaFader) in c:\dev\nquant\nQuant.Core\WuQuantizerBase.cs:line 94
   at nQuant.WuQuantizerBase.QuantizeImage(Bitmap image, Int32 alphaThreshold, Int32 alphaFader) in c:\dev\nquant\nQuant.Core\WuQuantizerBase.cs:line 28
   at nQuant.WuQuantizerBase.QuantizeImage(Bitmap image) in c:\dev\nquant\nQuant.Core\WuQuantizerBase.cs:line 22
   at Strabo.Core.Worker.ColorSegmentationWorker.Apply(String inputDir, String outputDir, String fileName, Int32 k, Int32 threadNumber) in C:\Users\ialok\GitHub\strabo-text-recognition\Strabo.CommandLine\Strabo.Core\Worker\ColorSegmentationWorker.cs:line 92
3/10/2017 2:33:10 PM ColorSegmentationWorker: Exception of type 'System.OutOfMemoryException' was thrown.
3/10/2017 2:33:10 PM Exception of type 'System.OutOfMemoryException' was thrown.
3/10/2017 2:33:10 PM    at nQuant.ColorData..ctor(Int32 dataGranularity, Int32 bitmapWidth, Int32 bitmapHeight) in c:\dev\nquant\nQuant.Core\ColorData.cs:line 19
   at nQuant.WuQuantizerBase.BuildHistogram(Bitmap sourceImage, Int32 alphaThreshold, Int32 alphaFader) in c:\dev\nquant\nQuant.Core\WuQuantizerBase.cs:line 94
   at nQuant.WuQuantizerBase.QuantizeImage(Bitmap image, Int32 alphaThreshold, Int32 alphaFader) in c:\dev\nquant\nQuant.Core\WuQuantizerBase.cs:line 28
   at nQuant.WuQuantizerBase.QuantizeImage(Bitmap image) in c:\dev\nquant\nQuant.Core\WuQuantizerBase.cs:line 22
   at Strabo.Core.Worker.ColorSegmentationWorker.Apply(String inputDir, String outputDir, String fileName, Int32 k, Int32 threadNumber) in C:\Users\ialok\GitHub\strabo-text-recognition\Strabo.CommandLine\Strabo.Core\Worker\ColorSegmentationWorker.cs:line 112
   at Strabo.Core.Worker.ColorSegmentationWorker.Apply(String intermediatePath, Int32 threadNumber) in C:\Users\ialok\GitHub\strabo-text-recognition\Strabo.CommandLine\Strabo.Core\Worker\ColorSegmentationWorker.cs:line 47
   at Strabo.Core.Worker.CommandLineWorker.Apply(InputArgs inputArgs, Boolean processLocalFiles, Double top, Double left, Double bottom, Double right) in C:\Users\ialok\GitHub\strabo-text-recognition\Strabo.CommandLine\Strabo.Core\Worker\CommandLineWorker.cs:line 167
   at Strabo.Test.TestCommandLineWorker.testBlockMaps() in C:\Users\ialok\GitHub\strabo-text-recognition\Strabo.CommandLine\Strabo.Test\TestCommandLineWorker.cs:line 347
3/10/2017 2:33:10 PM Process finished
```

**Comment by ialok** [comment]
> Possible Fix
-  Try different image processing libraries
[Aforge](http://www.aforgenet.com/framework/features/color_reduction.html) 
[Emgu CV](http://www.emgu.com/forum/viewtopic.php?t=15472) k-Means, octree
[SO: how-can-i-load-manipulate-a-huge-image-without-memory-issues ](http://stackoverflow.com/questions/13444526/how-can-i-load-manipulate-a-huge-image-without-memory-issues)

- Convert the image into smaller chunks, apply quantization algorithm on each chunk followed by a merge
[MATLAB: block-processing-large-images](https://www.mathworks.com/help/images/examples/block-processing-large-images.html)
[dealing-with-really-big-images-block-processing](http://blogs.mathworks.com/steve/2011/08/16/dealing-with-really-big-images-block-processing/)

Each link references specific articles for color quantization. We need to try each and then decide which one is the best. In case of block processing, the existing library can be used as the file size will reduce for each image

**Comment by ialok** [comment]
> Observations

When using median-cut algorithm provided by  __ColorImageQuantizer__ class of `AForge.Imaging.ColorReduction`, OutofMemory Exception is seen. Same exception was thrown by 
previous library
- We cannot assume that a library will handle large image(s) correctly
- Splitting on our end seems a better option

> Possible Places to Split
- Split image at the beginning of the pipeline @wangzyusc 
  * Run the whole pipeline for each smaller image
  * Combine the GeoJson output produced by all chunks

- Split image for one or more stage in the pipeline 
  * Execute few pipeline(s) for the smaller images
  * Combine/Stitch the images back to a processed large image (_smaller size_)
  * Execute the remaining pipeline with this new processed image

> Gotcha
- Image(s) need to be split at least during _ColorSegmentation_ and _TextDetection_
- While _ColorSegmentation_ does not need a large number of smaller images, _TextDetection_ 
fails if the image size is large (i.e split into more smaller images)
  - Splitting a source image of size 150Mb into 16 sub images for  _ColorSegmentation_  and 64 for 
_TextDetection_ seems to work
-  _TextDetection_ seems buggy. It fails when the image is not split and _overlap_ is zero(1,1,0) @yaoyichi @wangzyusc 

> **TODO: Enhancements**
- Pipeline is slow to process large images
- Efficient method to merge images: [Accord Automatic merging](https://www.codeproject.com/articles/95453/automatic-image-stitching-with-accord-net)

**Comment by ialok** [comment]
Code changes that enable splitting image during color segmentation seems to fix this problem.
